import { createClient } from '@supabase/supabase-js';
import type { ProductCategory, Product, Order, FarmerProfile, UserProfile } from './types';

export const SUPABASE_URL = "https://iyurbpfsvqzmdyaqinqi.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dXJicGZzdnF6bWR5YXFpbnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczMjkyODUsImV4cCI6MjEwMjkwNTI4NX0.QiHk-cjLDETbK385RqW3R40A3ePpTn1B0XgN4FOJs2Q";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Seed mock data for local demo testing and graceful fallbacks
export const DEFAULT_CATEGORIES: ProductCategory[] = [
  { id: 'cat-veg', name: 'Vegetables', slug: 'vegetables', icon: '🥕' },
  { id: 'cat-fruit', name: 'Fruits', slug: 'fruits', icon: '🍎' },
  { id: 'cat-grain', name: 'Grains & Cereals', slug: 'grains', icon: '🌾' },
  { id: 'cat-pulse', name: 'Pulses & Dal', slug: 'pulses', icon: '🌱' },
  { id: 'cat-spice', name: 'Spices & Herbs', slug: 'spices', icon: '🌶️' },
  { id: 'cat-dairy', name: 'Dairy & Ghee', slug: 'dairy', icon: '🥛' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    farmer_id: 'farmer-mock-1',
    category_id: 'cat-veg',
    name: 'Fresh Desi Tomatoes (देसी टमाटर)',
    description: 'Vine-ripened organic red tomatoes with rich aroma and natural sweetness. Freshly harvested.',
    price_per_unit: 35,
    unit: 'kg',
    stock: 120,
    harvest_date: new Date().toISOString().split('T')[0],
    farm_location: 'Lakhimpur Kheri, Uttar Pradesh',
    image_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    is_available: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'prod-2',
    farmer_id: 'farmer-mock-1',
    category_id: 'cat-veg',
    name: 'Farm Fresh Potatoes (आलू)',
    description: 'Crisp, starchy soil-fresh potatoes, completely free from chemical accelerators.',
    price_per_unit: 25,
    unit: 'kg',
    stock: 250,
    harvest_date: new Date().toISOString().split('T')[0],
    farm_location: 'Lakhimpur Kheri, Uttar Pradesh',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    is_available: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
  },
  {
    id: 'prod-3',
    farmer_id: 'farmer-mock-1',
    category_id: 'cat-grain',
    name: 'Sharbati Organic Wheat (शरबती गेहूं)',
    description: 'Premium quality golden grain harvested from rich fertile fields. Ideal for fluffy rotis.',
    price_per_unit: 42,
    unit: 'kg',
    stock: 500,
    harvest_date: new Date().toISOString().split('T')[0],
    farm_location: 'Lakhimpur Kheri, Uttar Pradesh',
    image_url: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    is_available: true,
    created_at: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
  },
  {
    id: 'prod-4',
    farmer_id: 'farmer-mock-1',
    category_id: 'cat-fruit',
    name: 'Sweet Farm Papaya (मीठा पपीता)',
    description: 'Naturally ripened, rich in fiber and vitamins.',
    price_per_unit: 45,
    unit: 'piece',
    stock: 0,
    harvest_date: new Date().toISOString().split('T')[0],
    farm_location: 'Lakhimpur Kheri, Uttar Pradesh',
    image_url: 'https://images.unsplash.com/photo-1617112848923-cc2234396a8d?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    is_available: false,
    created_at: new Date(Date.now() - 3600000 * 24 * 6).toISOString(),
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-982143',
    farmer_id: 'farmer-mock-1',
    consumer_id: 'user-c1',
    customer_name: 'Rajesh Sharma',
    customer_mobile: '9876543210',
    delivery_address: 'House 42, Gomti Nagar Sector 4',
    city: 'Lucknow',
    pincode: '226010',
    product_id: 'prod-1',
    quantity: 5,
    price_per_unit: 35,
    subtotal: 175,
    delivery_fee: 30,
    discount: 0,
    total_amount: 205,
    payment_status: 'paid',
    order_status: 'pending',
    delivery_slot: 'Morning 7:00 AM - 10:00 AM',
    notes: 'Please leave with security if doorbell not answered.',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: 'ORD-871209',
    farmer_id: 'farmer-mock-1',
    consumer_id: 'user-c2',
    customer_name: 'Pooja Verma',
    customer_mobile: '9812345678',
    delivery_address: 'Flat 302, Green Valley Apts',
    city: 'Lucknow',
    pincode: '226016',
    product_id: 'prod-3',
    quantity: 20,
    price_per_unit: 42,
    subtotal: 840,
    delivery_fee: 0,
    discount: 40,
    total_amount: 800,
    payment_status: 'paid',
    order_status: 'confirmed',
    delivery_slot: 'Evening 5:00 PM - 8:00 PM',
    notes: 'Handle with care',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'ORD-762111',
    farmer_id: 'farmer-mock-1',
    consumer_id: 'user-c3',
    customer_name: 'Amit Patel',
    customer_mobile: '9944332211',
    delivery_address: 'Shop 12, Market Road, Alambagh',
    city: 'Lucknow',
    pincode: '226005',
    product_id: 'prod-2',
    quantity: 50,
    price_per_unit: 25,
    subtotal: 1250,
    delivery_fee: 50,
    discount: 50,
    total_amount: 1250,
    payment_status: 'paid',
    order_status: 'completed',
    delivery_slot: 'Completed at 11:30 AM',
    notes: 'Regular wholesale buyer',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
  }
];

export const INITIAL_FARMER: FarmerProfile = {
  id: 'farmer-mock-1',
  user_id: 'user-mock-1',
  farm_name: 'Shukla Krishi Farm (शुक्ला जैविक फार्म)',
  farm_location: 'Lakhimpur Kheri',
  farm_size: '7.5 Acres',
  farming_type: 'organic',
  district: 'Lakhimpur Kheri',
  state: 'Uttar Pradesh',
  verification_status: 'verified',
  created_at: '2024-01-15T00:00:00Z',
};

export const INITIAL_USER: UserProfile = {
  id: 'user-mock-1',
  full_name: 'Vimal Shukla',
  email: 'vimalshukla282@gmail.com',
  mobile: '9876543210',
  village: 'Palia Kalan',
  district: 'Lakhimpur Kheri',
  state: 'Uttar Pradesh',
};
